name: Main
on: [push]

jobs:
  my_job:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Archive files
       # run: |
       #   sudo apt-get update
       #   sudo apt-get install zip
       #   zip -r archive.zip *
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #    cache: 'npm'
      #- run: npm install
     # runs:
     #     using: 'node16'
     #    main: 'main.js'
     run: |
      - name: Upload to gdrive
        uses: mohitVec/Demo@main
        with:
          credentials: secrets.GST_SECRET
          filename: "test.txt"
          folderId: secrets.FOLDER_SECRET
          #name: "documentation.zip" # optional string
          #overwrite: "true" # optional boolean
