# .github/workflows/main.yml
name: Main
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to gdrive
        uses: https://github.com/mohitVec/Demo@main
        with:
          credentials: ${{ secrets.AIzaSyBKvYg5k-OY1Yan1cyv7zT-mnwxfjg4tj4}}
          filename: "test-1"
          folderId: ${{ secrets.1GLk5JT3aotYUxd7vBW2-jaB65ZljrGfr }}
          #name: "documentation.zip" # optional string
          #overwrite: "true" # optional boolean
