name: Store readme in Drive
on: 
  push : { branches: [main] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: window-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload README.md to Google Drive
        uses: mohitVec/Demo@main
        with:
          target: README.md
          credentials: secrets.GST_SECRET          
          folder: 1h1kBO5kXivqtp2u8EMxFP4yPlCH7_HDO
