name: Store readme in Drive
on:
  push: { branches: [main] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: window-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload README.md to Google Drive
        uses: mohitVec/Demo@main
        with:
          target: README.md
          credentials: secrets.\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrAO1JaiUQ1d74\nelvHZHAluVGb6UQZQOjMrQVbc9ZCEN4vAl+r4bniP/sNPQqYRabcbtrv9WY3EyJg\nwQHZifuIjLYocnK8EPcGZR4ZQba2hLfkihO8eJlKEWDAk6F5tRjoekBqEeh3T9IO\nENqM2H634S6yQl3hkuGt++m8xPgpzjTmihyE8x8Y2iMxDXc5IFX6HHyfx6ZfXsEa\nhKeF+dfvZNnYP0h5YszDTy43XhsTMZ+2u7Wm/zxppw9oDU4iVOPgAcu6rV2mBdPX\nPxdXXf64wBZxgGoxiwM0yekhuQ0u9QtS0RBcT/JK2ajKCHmO+uJzEueLc1lWqvNj\nVb9r2UoLAgMBAAECggEALAVeEGMhzZaxAphFHixN7ngpeRBwtmuOQnpcAbHtOy6q\nc8GRrWa7enHsB/lpy89KaD6lX9Z1jMIBPJUTC9RIi1tl3T2xKZbYcK4BNJFFHvFF\ngbDF6ePF2lpk5M5caD9lfRtTj7qydFx4/6P5Dv8AiAeRBNSu5E3yiN5rymuOUvxV\ng7hmzBeQvWWrBlsHWx4unNhVt4y2zSQjDFxNOAvqNCv9kYsM7rBuXjsM1BnGW0U7\ngN3WyZFPG7OQnl9Djwk2AkGJgoYAujIYricUluCuiomWad/bnnpdb8HXbRST03/t\n+hj4lKO69PNKLg2GwhhVbxrt/X/dHL1HhOKg9/R6WQKBgQDgxO9+PDmnOcD5XQ6G\nPdst/3KbVE1UtraYVi3rbexcb649UxB/1HBl0ExtTcDS7Sg8AFy4vTsqQWY0/l4x\n3lqJSUeh+Q+ScPOBzOVpiUWedTJ3SAqtqPLl/yZmUGP157kzA58b4P3DOIykLw71\n28xl4Gj7MnCmqiN/Y+gBEWbK5wKBgQDCw4q1R8NVeQBsZVyVkkIUdwufSjJX8Wq/\nUMTAnEqwvjZCPgHoOa01PpYAN0+lFqQuvRKfY8shub8M2h/5tbm6LXzJuCe8i9bH\nmsO705Gj2GxM6Xt62wT5MylAZwYFU4dEe/GnEe7gWpIaY9ZAxfcvRSJrEvwiLaNx\n9kLo4IhnPQKBgGvqAXYhIikIkH7oz7Vh8151O6gZ5HrcsnQXRDq5bva+Y/Brdgt5\ninFHfbooz4A1ftC398x2hfZ2qcSdr8nPkLZDKZI5iuFrO25BWo+96V/3ssAUJZRU\n/jGwu9X5mNSSaZd1kKmI7y0QdG3LbipaWhs7kAuynuVV4G8kH1qL6UdXAoGBAL8R\nIDGpXjqqwzyTz9k4K7Vx+CfjnTHjN6rKLMscSLXNVON1e197va1/YZ6CpJK7fIQR\nnoRZXT0PwRp1nmrV2YeI+mPWUr1InoMhFCZebwFC3zQw1Z934BAtHan9p81v3ULV\nKQOStzrH/47+JIFU9KMd+p76d/l7tl2ljoxxQb+tAoGASymM/QEfSJ4CCjhBznvH\nQq5n3x65gQIHtm2nVJcEKB02lfU29UjVOm3KWr2kQHbNxXbGed0t1NSy6mFc2dek\n2eKUZ4KKnkcpRynUu5j/3HBvhuX7czwZ5I1Q2Zg7Rp74oFf9wCfcf8Kj+Gmhoe/R\n3RL8kVtalIIaLnaDG8s6s28=\n
          folder: 1h1kBO5kXivqtp2u8EMxFP4yPlCH7_HDO
