
name: Main
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r test.zip *
      runs:
          using: "composite"
          steps: 
            steps:
            - name: Echo
              shell: bash
              run: |
                echo Heyyyyy
      - name: Upload to gdrive
        uses: mohitVec/Demo@main
        with:
          credentials: GST_SECRET
          filename: "test.zip"
          folderId: FOLDER_SECRET
          name: "documentation.zip" # optional string
          overwrite: "true" # optional boolean
