name: first-github-action
on: [push]
jobs:

  write-to-console:
    runs-on: windows-latest
    steps:
      - run: echo 'Hello world!'
      - run:  python --version
      - run: git --version
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
  
        
        
