
name: Main
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r test.zip *
      
      - name: Upload to gdrive
        uses: mohitVec/Demo@main
        
        with:
          credentials: GST_SECRET
          filename: "test.zip"
          folderId: FOLDER_SECRET
          name: "documentation.zip" # optional string
          overwrite: "true" # optional boolean
