name: action2
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest  # windows-latest | macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Archive files
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install zip
      #    zip -r archive.zip *

      - name: Upload to gdrive
        uses: mohitVec/Demo@main
        with:
          credentials: ${{ secrets.GST_SECRET }}
          filename: "test.txt"
          folderId: ${{ 1h1kBO5kXivqtp2u8EMxFP4yPlCH7_HDO }}
          #name: "documentation.zip" # optional string
          #overwrite: "true" # optional boolean
